project:
  type: website

website: 
  page-navigation: true
  title: "TME 310 A - Fall 2025"
  description: "Homepage for TME 310 A - Computational Physical Modeling at UW Tacoma"
  site-url: "https://UWT-TME-310.github.io/TME_310_students/"

  repo-url: https://github.com/UWT-TME-310/TME_310_students
  repo-actions: [source, issue]

  sidebar:
    background: "#ffffff"
    logo: "website/reference/modeling_framework.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/UWT-TME-310/TME_310_students
        target: _blank
       
    style: "docked"
    search: true
    contents:
      - section: "TME 310A"
        href: index.qmd
        contents:
        - section: "Course information"
          contents:
            - href: website/start_here.qmd
            - href: website/course_syllabus.qmd
            - href: website/instructor.qmd
            - href: website/accessibility_accommodations.qmd
            - href: website/being_successful_student.qmd
            - href: website/grading_policies.qmd
            - href: website/homework_format.qmd
            - href: website/github_codespace.qmd
        - text: ---
        - section: "Weekly materials"
          contents:
            - href: website/weeks/week_1.qmd
            - href: website/weeks/week_2.qmd
            - href: examples/plotting_a_sine_wave.ipynb
        - text: ---
        - section:
          href: website/resources.qmd
        - text: ---   
        - section: "Project"
          contents:
            - href: website/project_description.qmd
            - href: website/project_01.qmd
            - href: website/project_02.qmd
            - href: website/project_03.qmd
      

format:
  html:
    link-external-newwindow: true
    link-source-notebook: true
    theme:
      - cosmo
    css: website/styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto