# Example scripts

The table below contains some example scripts using basic course concepts.

| Script link | Notes |
|----|----|
| [Python basics](/examples/02_python_basics.ipynb) | |
| [Plotting a sine wave](/examples/00_plotting_a_sine_wave.ipynb) | Basic use of `matplotlib` |
| [Parachute problem](/examples/03_parachute.ipynb) |  |
| [Parachute problem (copilot solution)](/examples/03_parachute_copilot.ipynb) |  |
| [Parachute functions](/examples/05_parachute_functions.ipynb) |  |
| [Matplotlib quick reference](/examples/matplotlib_quick_ref.ipynb) | Plots with some styling options |
| [Quiz corrections for extra credit](/examples/quiz_correction.ipynb) | An example to follow if doing extra credit to make up points lost on a quiz |
| [Dartboard approximation of $\pi$](/examples/07_dartboard_pi.ipynb) | Convergence and error tolerance example with plots |
| [Homework 3 notes](/examples/hw03_grading_notes.ipynb) | My notes on some of the common approaches I saw while grading homework 3. |
| [Homework 4 notes](/examples/hw04_grading_notes.ipynb) | My notes on things I observed while grading homework 4. |
| [Root-finding example code](/examples/root_finding_examples.ipynb) | |
