# Project Part 3 - enhanced pile-driving app

<!-- Assignment repo: [project_03]() -->

## Purpose

Demonstrate the coding skills learned in the course to develop a notebook that could be **useful for engineering professionals** working on pile-driving projects.

## Building on Part 2

Your goal for Part 3 of the course project is to enhance the a basic pile-driving app you developed in Part 2 (you are also allowed to use the Part 2 example submission as a starting point for Part 3).
The app will produce an engineering report on a specific aspect of pile-driving based on the enhancement option selected by your group.

There are several ways that the basic pile-driving app could be enhanced.
Descriptions of suggested enhancements are listed below.
Your project group should choose one of the suggested enhancements below OR propose an enhancement to be approved by your instructor.

### Enhancement Options

For all the enhancement options, refer to the [pile, hammer, PDA, and environmental parameters](03_pile_hammer_specs.md) for relevant values.

<!-- 1. **Audio-video saximeter**
   
   A Saximeter is an instrument that uses sound to determine the timing of hammer blows during pile-driving. 
   Traditionally, a field engineer uses a saximeter to record blows per minute (BPM) while watching for the pile to have been driven a certain length (usually one foot). 
   By manually pressing a button on the saximeter, the field engineer records the time between 1-foot driving intervals, which the saximeter uses (in combination with its audio-based record of blows) to calculate blows per foot (BPF).

   The *Audio-video saximeter* enhancement will involve using a video of a pile-driving installation to create the same data as are traditionally captured by the field engineer and saximeter.
   The data interpreted from the video, will produce a pile-driving log and the associated plots from Part 2.

   The focus of this option is the audio/video analysis. -->

1. **Diesel hammer combustion**

   Open-ended diesel hammers consist of a single cylinder containing a heavy piston called a ram. 
   During operation, fuel ignition launches the  ram up into the air. 
   When the ram falls back down, it compresses and heats an air/fuel mixture in the piston, reaching its ignition temperature and starting the process over again.

   The *Diesel hammer combustion* enhancement will involve creating a model of the combustion process - the increasing pressure and temperature due to the falling piston, the energy released by fuel ignition, and the resulting displacement of the piston.
   The model will provide a means of calculating the fuel needed to achieve different piston heights.
   Combined with a pile-driving log containing blows per minute (BPM) and blows per foot (BPF), the model will show the fuel consumption during the pile-driving process.
   [**A mathematical framework for the combustion model will be provided to you.**](03_diesel_hammer_combustion.ipynb)

   The focus of this option is the fuel consumption and carbon emissions for pile installation.


2. **Pile Driving Analysis (PDA) from instrumentation**

   Pile Driving Analysis (PDA) is the name of a specific set of instruments and calculations used to measure wave transmission through a pile as it's driven and estimate its capacity.
   Generally, PDA is performed on only a small percentage of piles in a given project because it's expensive to perform and slows down the construction (because of the instrument installation).
   PDA data contains measurements of **strain** and **acceleration** signals that can be used to calculate the force and speed of pressure waves traveling through the pile. 
   This data can be interpreted to determine an estimate of the pile's capacity, the maximum tension and compression stresses in the pile, and detect whether the pile has been damaged.

   The *PDA instrumentation* enhancement will use data from one or more blows at the end of driving to produce a capacity estimate to compare to the estimate from a pile-driving log. 
   Additionally, the pile stresses and damage indications (if any) will be reported and compared to the material strength as a quality control check on the pile's structural integrity. 
   [**A mathematical framework for PDA analysis will be provided to you.**](03_PDA.ipynb)

   The focus of this option is quality control and capacity verification.


1. **Environmental noise assessment**

   Pile-driving is a noisy process.
   The noise from pile-driving can be a nuisance to neighboring properties and disturbing (and even lethal) to wildlife.
   Sound from pile-driving comes from the impact between the pile and hammer and from the deformation of the pile as compression and tension waves travel through the pile.
   The noise from the waves traveling through the pile are particularly important under water, where they have the most impact on wildlife.

   The *Environmental noise assessment* enhancement will use the PDA strain and velocity measurements to estimate the volume in air and water from a single blow to the pile.
   The noise attenuation with distance from the pile will be compared to different thresholds, providing an estimate for the distance where various noise issues are of concern.
   Combined with a pile-driving log with blows per minute (BPM) and blows per foot (BPF), the noise model will provide a range of distances and time durations over which the noise issues are of concern.
   [**A mathematical framework for the sound volume model will be provided to you.**](03_environmental_noise.ipynb)

   The focus of this option is environmental regulation compliance.

<!-- 
1. **Subsurface interpretation using data clustering**
   
   The data in the pile-driving log can be used to estimate the final pile capacity, but it also shows how the capacity of the pile changed as it was driven through the soil.
   Different soil layers are likely to have different levels of resistance to driving (and therefore different capacities).
   For a pile-driving project with several piles, combining all the pile-driving logs may provide clues to the number of distinct geologic layers the piles were driven through.

   The *Subsurface interpretation using data clustering* enhancement is **part of an active research project** on pile-driving data interpretation.
   This enhancement will use multiple (~100) pile-driving logs to develop a dataset of pile-driving resistances across a project site.
   Using data clustering techniques, an analysis of the dataset will produce a report on the number of distinct geologic layers at the site.

   The focus of this option is research of new data interpretation methods. 
   As such, it has the potential to be both exciting and challenging. 
   Exciting because it may show a result that no one's seen before.
   Challenging because there's less likely to be a "right" answer or a "best" approach to the problem. -->


## Requirements

### User "input"
User input should be limited to changing file names or variable values within the notebook.
Do not use Python's `input()` function to prompt the notebook user.
The notebook should include valid values when submitted so that it can run without the user needing to change file names or variable values.

### Documentation

#### In the notebook
The notebook should contain instructions for users and technical background on the analysis being performed.
The instructions should tell the user what inputs are needed for the analysis to run (e.g., the name of a pile log file, or PDA data file).
The technical background should explain how the input is used in the analysis and what the analysis results should be interpreted.

#### In the support files
At least one .py file should be used to perform the majority of the analysis.
This file should contain Python **functions** with docstrings.
Any individual who understands Python should be able to view the supporting code and understand how each function works by reading the docstrings. 
At a minimum, docstrings should include:

1. A description of the function's purpose.
2. A list of the function's input parameters, including whether they have default values and what units the should be in.
3. A list of the function's output parameters, including what units they will be in.

### Validation

Your notebook should include a validation section where your analysis results are compared to some external source to check whether they're reasonable.

| Project option | Validation source | Validation goal | 
|-------|-------|-------|
| Diesel hammer combustion | [DELMAG Diesel Pile Hammers specifications](https://www.delmag.com/products.html?file=files/content/pdf_DELMAG_Prospekte/DELMAG_DB_deen.pdf&cid=19333)| Find a hammer from the catalogue that seems like a good match for the project hammer specs. Compare the fuel use from the specifications sheet (reported in Litres per hour) to your analysis. Which do you think is more accurate? |
| PDA instrumentation | Pile capacity estimates from the pile-driving log. | Compare the capacity estimates at the appropriate elevations from the two data sources. Is the capacity from the log higher or lower than from the PDA data? What adjustment, if any, could your recommend to the $S_o$ capacity estimate to improve its accuracy? | 
| Environmental noise assessment | [Marine mammal monitoring plan for NAVMAG Indian Island - Ammo Wharf Maintenance and Pile Replacement Program](https://www.fisheries.noaa.gov/s3/2023-10/USNAVYNAVMAGIndianIsland-2024LOA-DraftMonPlan-OPR1.pdf)| Compare the monitoring distances for concrete piles in the monitoring plan for any species relevant to your analysis. Are the monitoring distances closely related to the threshold distances from your analysis? What adjustments, if any would you recommend making to either the monitoring plan distances based on your analysis? | 



### Figures

The figures needed will depend on the enhancement option.
All enhancement options will need to include BPM, BPF, and capacity plots with the same requirements as in Part 2.

Additional figures needed for specific enhancement options are described below.
All plots should have an accurate title and axes labeled with the appropriate units.
<!-- 
#### Audio-video saximeter

Include plots of 

- pile displacement (y-axis) vs. time (x-axis) 
- pile displacement (y-axis) vs. number of pile blows (x-axis) -->

#### Diesel hammer combustion

Include plots of 

- The relationship between piston height (y-axis) and fuel volume (x-axis)
- Pile tip elevation (y-axis) and fuel consumption (x-axis) for the driving log in the same orientation as the pile-driving log plots.

#### PDA instrumentation

Add the Case method capacity estimates at the appropriate elevations to the pile capacity plot for the validation component.

For both PDA blows, include plots of:

- The PDA force and velocity*Z (y-axis) vs time (x-axis).
- The Case method total, dynamic, and static capacity (y-axis) vs. time (x-axis). Include markers to indicate the points on the plot corresponding to the peak static capacity and the frictional static capacity.
- The displacement (y-axis) and force (x-axis) in the pile from the hammer blow captured by the PDA data.

#### Environmental noise assessment

Include plots of

- The sound volume in air (y-axis) and water (y-axis) vs. distance (x-axis) from the pile from the hammer blow captured by the PDA data. The plot should include at least one environmental noise limit per medium.
- Pile tip elevation (y-axis) and distance to environmental thresholds (x-axis) for the driving log in the same orientation as the pile-driving log plots.


## Submission

Your project will be submitted by pushing your work to GitHub (same as the homework submission procedure).
At a minimum, the submission should include:

1. Your app's notebook (one `.ipynb` file)
2. Your app's support script (one or more `.py` files)
3. All the `.csv` files included in the project repository.


<!-- ## Rubric
## Grading rubric

Your submission will be graded by the instructor with the following rubric:


| Category | Criteria | Points |
|----|----|----|
| User input | asdf |  __ / 10  |
| Documentation | docs |  __ / 10 |
| Figures | asdf |  __ / 10 |
| Validation | docs |  __ / 10 |
| Support code |  The functions that perform the app's calculations are imported into the app from one or more supporting Python files. The functions are well documented (purpose, inputs and outputs described in a docstring). |  __ / 10 | -->